# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSite1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        AddWindow.setObjectName("AddWindow")
        AddWindow.resize(800, 667)
        AddWindow.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:20px;\n"
"}\n"
"QFrame\n"
"{\n"
"    background:rgba(0,0,0,0.8);\n"
"    border-radius:15px\n"
"    \n"
"}\n"
"#AddWindow{\n"
"    border-image: url(:/pref0/images/InterfaceChoisie.jpeg);\n"
"}\n"
"QToolButton\n"
"{\n"
"    background:#ffb860;\n"
"    border-radius:15px;\n"
"}\n"
"QLabel\n"
"{\n"
"    color:#ffb860;\n"
"    background:transparent;\n"
"    \n"
"}\n"
"QPushButton\n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#ffb860;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:white;\n"
"}\n"
"QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"font-size:14px;\n"
"}\n"
"QRadioButton{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(AddWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(170, 80, 471, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(190, 30, 111, 31))
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 460, 291, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_2.clicked.connect(self.insert_data)

        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setEnabled(True)
        self.lineEdit_6.setGeometry(QtCore.QRect(210, 95, 201, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setEnabled(True)
        self.lineEdit_7.setGeometry(QtCore.QRect(210, 150, 201, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setEnabled(True)
        self.lineEdit_8.setGeometry(QtCore.QRect(210, 229, 201, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_9.setEnabled(True)
        self.lineEdit_9.setGeometry(QtCore.QRect(210, 310, 201, 31))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 91, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10, 160, 171, 41))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 220, 91, 51))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(10, 300, 81, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(10, 360, 201, 61))
        self.label_12.setObjectName("label_12")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(210, 380, 61, 31))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(320, 380, 61, 31))
        self.radioButton_2.setObjectName("radioButton_2")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(370, 20, 91, 81))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pref1/images/AddIcon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(50, 50))
        self.toolButton.setObjectName("toolButton")
        AddWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AddWindow)
        self.statusbar.setObjectName("statusbar")
        AddWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddWindow)
        QtCore.QMetaObject.connectSlotsByName(AddWindow)

    def insert_data(self):
        try:
            mydb = mysql.connector.connect(
                host="",
                user="",
                password="",
                database="review_site"
            )

            mycursor = mydb.cursor()

            URL = self.lineEdit_6.text()
            designation = self.lineEdit_7.text()
            categorie = self.lineEdit_8.text()
            city = self.lineEdit_9.text()
            if self.radioButton.isChecked():
                handsite = True
            elif self.radioButton_2.isChecked():
                handsite = False

            query=("INSERT INTO SITES (DESSITE,CODECAT,VILLESITE,LIENSITE,HANDSITE) VALUES (%s,(select CODECAT FROM Categories WHERE DESCAT = %s),%s,%s,%s)")
            value = (designation,categorie,city,URL,handsite)
            mycursor.execute(query, value)
            mydb.commit()
            self.pushButton_2.setText("Site Added")
            mycursor.close()
            mydb.close()
        except mysql.connector.Error as e:
            self.pushButton_2.setText("Try Again")


    def retranslateUi(self, AddWindow):
        _translate = QtCore.QCoreApplication.translate
        AddWindow.setWindowTitle(_translate("AddWindow", "MainWindow"))
        self.label_7.setText(_translate("AddWindow", "<html><head/><body><p>Add Site</p></body></html>"))
        self.pushButton_2.setText(_translate("AddWindow", "Add"))
        self.label_8.setText(_translate("AddWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">URL:</span></p></body></html>"))
        self.label_9.setText(_translate("AddWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Site designation:</span></p><p align=\"center\"><br/></p></body></html>"))
        self.label_10.setText(_translate("AddWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Site category:</span></p></body></html>"))
        self.label_11.setText(_translate("AddWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Site City:</span></p></body></html>"))
        self.label_12.setText(_translate("AddWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">The site is accessible</span></p><p><span style=\" font-size:10pt;\">to the disabled:</span></p></body></html>"))
        self.radioButton.setText(_translate("AddWindow", "yes"))
        self.radioButton_2.setText(_translate("AddWindow", "NO"))
import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddWindow = QtWidgets.QMainWindow()
    ui = Ui_AddWindow()
    ui.setupUi(AddWindow)
    AddWindow.show()
    sys.exit(app.exec_())
