# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_DeleteWindow(object):
    def setupUi(self, DeleteWindow):
        DeleteWindow.setObjectName("DeleteWindow")
        DeleteWindow.resize(766, 575)
        DeleteWindow.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:20px;\n"
"}\n"
"#DeleteWindow{\n"
"    border-image: url(:/pref0/images/InterfaceChoisie.jpeg);\n"
"}\n"
"\n"
"QFrame\n"
"{\n"
"    background:rgba(0,0,0,0.8);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton\n"
"{\n"
"background: #ffb860;\n"
"border-radius:15px;\n"
"}\n"
"QToolButton\n"
"{\n"
"background: #ffb860;\n"
"border-radius:15px;\n"
"}\n"
"QToolButton\n"
"{\n"
"background: #ffb860;\n"
"border-radius:15px;\n"
"}\n"
"QLabel\n"
"{\n"
"    color:#ffb860;\n"
"    background:transparent;\n"
"}\n"
"QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(DeleteWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(160, 90, 431, 331))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 40, 111, 31))
        self.label.setObjectName("label")

        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(100, 220, 231, 41))
        self.toolButton.setObjectName("toolButton")



        self.toolButton.clicked.connect(self.delete_data)

        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(110, 130, 171, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 120, 31, 31))
        self.pushButton_2.setText("")

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pref1/images/SearchIcon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 64))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 60, 61, 51))
        self.pushButton.setText("")

        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pref1/images/DeleteIcon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(20, 64))
        self.pushButton.setObjectName("pushButton")
        DeleteWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DeleteWindow)
        self.statusbar.setObjectName("statusbar")
        DeleteWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteWindow)

    def delete_data(self):
        try:
            mydb = mysql.connector.connect(
                host="",
                user="",
                password="",
                database="review_site"

            )

            mycursor = mydb.cursor()



            delete_site = (
                "DELETE FROM Sites WHERE LIENSITE = %s ")

            url = (self.lineEdit.text(), )

            mycursor.execute(delete_site, url)
            myresult = mycursor.fetchall()
            if myresult == None:
                self.toolButton.setText("Try again")
            else:
                self.toolButton.setText("Site deleded")
            mydb.commit()
            mycursor.close()
            mydb.close()

        except mysql.connector.Error as e:
            print("Error Deleting Data")


    def retranslateUi(self, DeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteWindow.setWindowTitle(_translate("DeleteWindow", "MainWindow"))
        self.label.setText(_translate("DeleteWindow", "Delete Site"))
        self.toolButton.setText(_translate("DeleteWindow", "Delete"))
        self.lineEdit.setText(_translate("DeleteWindow", "URL"))
import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DeleteWindow = QtWidgets.QMainWindow()
    ui = Ui_DeleteWindow()
    ui.setupUi(DeleteWindow)
    DeleteWindow.show()
    sys.exit(app.exec_())
