# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manageSite1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from AddInterface3 import Ui_AddWindow
from DeleteInterface2 import Ui_DeleteWindow
from ModifyInterface3 import Ui_ModifyWindow


class Ui_ManageWindow(object):

    def openAdd(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AddWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openDelete(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_DeleteWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def openModify(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_ModifyWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, ManageWindow):
        ManageWindow.setObjectName("ManageWindow")
        ManageWindow.resize(806, 588)
        ManageWindow.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:24px;\n"
"}\n"
"QFrame\n"
"{\n"
"    background:rgba(0,0,0,0.8);\n"
"    border-radius:15px\n"
"    \n"
"}\n"
"#ManageWindow{\n"
"    border-image: url(:/pref0/images/InterfaceChoisie.jpeg);\n"
"}\n"
"QToolButton\n"
"{\n"
"    background:#ffb860;\n"
"    border-radius:15px;\n"
"}\n"
"QLabel\n"
"{\n"
"    color:#ffb860;\n"
"    background:transparent;\n"
"}\n"
"QPushButton\n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#ffb860;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:white;\n"
"}\n"
"QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"font-size:14px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ManageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(220, 110, 441, 391))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 30, 161, 51))
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(50, 90, 81, 81))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pref1/images/AddIcon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(39, 39))
        self.toolButton.setObjectName("toolButton")

        self.toolButton.clicked.connect(self.openAdd)

        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setGeometry(QtCore.QRect(280, 80, 81, 81))
        self.toolButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pref1/images/ModifyIcon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(39, 39))
        self.toolButton_2.setObjectName("toolButton_2")

        self.toolButton_2.clicked.connect(self.openModify)

        self.toolButton_3 = QtWidgets.QToolButton(self.frame)
        self.toolButton_3.setGeometry(QtCore.QRect(160, 220, 81, 81))
        self.toolButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pref1/images/DeleteIcon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setIconSize(QtCore.QSize(39, 39))
        self.toolButton_3.setObjectName("toolButton_3")

        self.toolButton_3.clicked.connect(self.openDelete)

        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 180, 81, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(290, 170, 101, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(180, 310, 111, 41))
        self.label_4.setObjectName("label_4")
        self.toolButton_4 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_4.setGeometry(QtCore.QRect(370, 60, 111, 81))
        self.toolButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pref1/images/ManageSiteIcon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_4.setIcon(icon3)
        self.toolButton_4.setIconSize(QtCore.QSize(65, 65))
        self.toolButton_4.setObjectName("toolButton_4")
        ManageWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ManageWindow)
        self.statusbar.setObjectName("statusbar")
        ManageWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ManageWindow)
        QtCore.QMetaObject.connectSlotsByName(ManageWindow)

    def retranslateUi(self, ManageWindow):
        _translate = QtCore.QCoreApplication.translate
        ManageWindow.setWindowTitle(_translate("ManageWindow", "MainWindow"))
        self.label.setText(_translate("ManageWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">Manage Site</span></p></body></html>"))
        self.label_2.setText(_translate("ManageWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Add </span></p></body></html>"))
        self.label_3.setText(_translate("ManageWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Modify</span></p></body></html>"))
        self.label_4.setText(_translate("ManageWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Delete</span></p></body></html>"))
import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManageWindow = QtWidgets.QMainWindow()
    ui = Ui_ManageWindow()
    ui.setupUi(ManageWindow)
    ManageWindow.show()
    sys.exit(app.exec_())
