# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModifyInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_ModifyWindow(object):

    def setupUi(self, ModifyWindow):
        ModifyWindow.setObjectName("ModifyWindow")
        ModifyWindow.resize(934, 758)
        ModifyWindow.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:20px;\n"
"}\n"
"QFrame\n"
"{\n"
"    background:#333;\n"
"    background:rgba(0,0,0,0.8);\n"
"\n"
"}\n"
"#ModifyWindow{\n"
"    border-image: url(:/pref0/images/InterfaceChoisie.jpeg);\n"
"}\n"
"QPushButton\n"
"{\n"
"background: #ffb860;\n"
"border-radius:15px;\n"
"}\n"
"QToolButton\n"
"{\n"
"background: #ffb860;\n"
"border-radius:15px;\n"
"}\n"
"QLabel\n"
"{\n"
"    color:#ffb860;\n"
"    background:transparent;\n"
"\n"
"}\n"
"QPushButton\n"
"{\n"
"color:Black;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"color:#333;\n"
"border-radius:15px;\n"
"background:#49ebff;\n"
"}\n"
"QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}\n"
"QRadioButton{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(ModifyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(220, 100, 481, 591))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(180, 50, 111, 41))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(110, 500, 261, 31))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.modify_data)

        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(220, 140, 211, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 200, 211, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 260, 211, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 320, 211, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 171, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 260, 141, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 320, 111, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 390, 201, 41))
        self.label_6.setObjectName("label_6")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(240, 400, 61, 31))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(350, 400, 71, 31))
        self.radioButton_2.setObjectName("radioButton_2")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(420, 70, 81, 61))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pref1/images/ModifyIcon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(30, 64))
        self.toolButton.setObjectName("toolButton")
        ModifyWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ModifyWindow)
        self.statusbar.setObjectName("statusbar")
        ModifyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ModifyWindow)
        QtCore.QMetaObject.connectSlotsByName(ModifyWindow)



    def modify_data(self):
        try:
            mydb = mysql.connector.connect(
                host="",
                user="",
                password="",
                database="review_site"

            )

            mycursor = mydb.cursor()

            url = self.lineEdit.text()
            designation = self.lineEdit_2.text()
            category = self.lineEdit_3.text()
            city = self.lineEdit_4.text()
            if self.radioButton.isChecked():
                handSite = True
            elif self.radioButton_2.isChecked():
                handSite = False
            add_user = (
                "UPDATE Sites SET DESSITE = %s , VILLESITE = %s ,HANDSITE = %s, CODECAT = (select CODECAT FROM Categories WHERE DESCAT = %s) WHERE LIENSITE = %s ")

            mycursor.execute(add_user, (designation,city, handSite, category, url))

            mydb.commit()
            self.pushButton.setText("succeffuly modified")
            mycursor.close()
            mydb.close()

        except mysql.connector.Error as e:
            print("Error Updating Data")
    def retranslateUi(self, ModifyWindow):
        _translate = QtCore.QCoreApplication.translate
        ModifyWindow.setWindowTitle(_translate("ModifyWindow", "MainWindow"))
        self.label.setText(_translate("ModifyWindow", "Modify Site"))
        self.pushButton.setText(_translate("ModifyWindow", "Modify"))
        self.lineEdit.setText(_translate("ModifyWindow", "url"))
        self.lineEdit_2.setText(_translate("ModifyWindow", "designation"))
        self.lineEdit_3.setText(_translate("ModifyWindow", "category"))
        self.lineEdit_4.setText(_translate("ModifyWindow", "country"))
        self.label_2.setText(_translate("ModifyWindow", "URL:"))
        self.label_3.setText(_translate("ModifyWindow", "Site Designation:"))
        self.label_4.setText(_translate("ModifyWindow", "Site Category:"))
        self.label_5.setText(_translate("ModifyWindow", "Site City:"))
        self.label_6.setText(_translate("ModifyWindow", "the site is accessible \n"
"to the disabled:"))
        self.radioButton.setText(_translate("ModifyWindow", "YES"))
        self.radioButton_2.setText(_translate("ModifyWindow", "NO"))
import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModifyWindow = QtWidgets.QMainWindow()
    ui = Ui_ModifyWindow()
    ui.setupUi(ModifyWindow)
    ModifyWindow.show()
    sys.exit(app.exec_())
