# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'review1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Review(object):
    def setupUi(self, Review):
        Review.setObjectName("Review")
        Review.resize(773, 600)
        Review.setStyleSheet("*{\n"
"    font-family:century gothic;\n"
"    font-size:24px;\n"
"}\n"
"QFrame\n"
"{\n"
"    background:rgba(0,0,0,0.8);\n"
"    border-radius:15px\n"
"    \n"
"}\n"
"#Review{\n"
"    border-image: url(:/pref0/images/InterfaceChoisie.jpeg);\n"
"}\n"
"QToolButton\n"
"{\n"
"    background:#ffb860;\n"
"    border-radius:15px;\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"    color:#ffb860;\n"
"    background:transparent;\n"
"}\n"
"QPushButton\n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:#ffb860;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    color:#333;\n"
"    border-radius:15px;\n"
"    background:white;\n"
"}\n"
"QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"font-size:14px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Review)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(210, 100, 371, 441))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(120, 20, 101, 31))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(70, 390, 211, 31))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.insert_data)

        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(70, 60, 231, 21))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setGeometry(QtCore.QRect(310, 60, 31, 21))
        self.toolButton_2.setStyleSheet("QToolButton\n"
"{\n"
"    background:#ffb860;\n"
"    border-radius:5px;\n"
"}")
        self.toolButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pref1/images/SearchIcon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setObjectName("toolButton_2")

        #self.toolButton_2.clicked.connect(self.fetchURL)

        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 210, 301, 171))
        self.lineEdit_2.setStyleSheet("QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"border-top:1px solid #717072;\n"
"border-left:1px solid #717072;\n"
"border-right:1px solid #717072;\n"
"font-size:14px;\n"
"\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.toolBtn4 = QtWidgets.QToolButton(self.frame)
        self.toolBtn4.setGeometry(QtCore.QRect(200, 90, 21, 21))
        self.toolBtn4.setStyleSheet("QToolButton\n"
"{\n"
"    background:#ffb860;\n"
"    border-radius:10px;\n"
"}")
        self.toolBtn4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pref1/images/StarIcon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBtn4.setIcon(icon1)
        self.toolBtn4.setIconSize(QtCore.QSize(15, 15))

        ##star1
        self.toolBtn4.setObjectName("toolBtn4")
        self.toolBtn4.clicked.connect(self.rate_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)

        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 120, 121, 21))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"font-size:14px;\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.toolBtn1 = QtWidgets.QToolButton(self.frame)
        self.toolBtn1.setGeometry(QtCore.QRect(110, 90, 21, 21))
        self.toolBtn1.setStyleSheet("QToolButton\n"
"{\n"
"    background:#ffb860;\n"
"    border-radius:10px;\n"
"}")
        self.toolBtn1.setText("")
        self.toolBtn1.setIcon(icon1)
        self.toolBtn1.setIconSize(QtCore.QSize(15, 15))
        #star2
        self.toolBtn1.setObjectName("toolBtn1")
        self.toolBtn1.clicked.connect(self.rate_1)
        self.toolBtn3 = QtWidgets.QToolButton(self.frame)
        self.toolBtn3.setGeometry(QtCore.QRect(170, 90, 21, 21))
        self.toolBtn3.setStyleSheet("QToolButton\n"
"{\n"
"    background:#ffb860;\n"
"    border-radius:10px;\n"
"}")
        self.toolBtn3.setText("")
        self.toolBtn3.setIcon(icon1)
        self.toolBtn3.setIconSize(QtCore.QSize(15, 15))
        #star3
        self.toolBtn3.setObjectName("toolBtn3")
        self.toolBtn3.clicked.connect(self.rate_3)
        self.toolBtn2 = QtWidgets.QToolButton(self.frame)
        self.toolBtn2.setGeometry(QtCore.QRect(140, 90, 21, 21))
        self.toolBtn2.setStyleSheet("QToolButton\n"
"{\n"
"    background:#ffb860;\n"
"    border-radius:10px;\n"
"}")
        self.toolBtn2.setText("")
        self.toolBtn2.setIcon(icon1)
        self.toolBtn2.setIconSize(QtCore.QSize(15, 15))
        #star4
        self.toolBtn2.setObjectName("toolBtn2")
        self.toolBtn2.clicked.connect(self.rate_2)
        self.toolBtn5 = QtWidgets.QToolButton(self.frame)
        self.toolBtn5.setGeometry(QtCore.QRect(230, 90, 21, 21))
        self.toolBtn5.setStyleSheet("QToolButton\n"
"{\n"
"    background:#ffb860;\n"
"    border-radius:10px;\n"
"}")
        self.toolBtn5.setText("")
        self.toolBtn5.setIcon(icon1)
        self.toolBtn5.setIconSize(QtCore.QSize(15, 15))
        #star5
        self.toolBtn5.setObjectName("toolBtn5")
        self.toolBtn5.clicked.connect(self.rate_5)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 47, 61))
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"    color:#ffb860;\n"
"    background:transparent;\n"
"    font-size:16px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_rate = QtWidgets.QLabel(self.frame)
        self.label_rate.setGeometry(QtCore.QRect(290, 90, 47, 31))
        self.label_rate.setStyleSheet("QLabel\n"
"{\n"
"    color:#ffb860;\n"
"    background:transparent;\n"
"    font-size:14px;\n"
"}")
        self.label_rate.setObjectName("label_rate")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 111, 31))
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"    color:#ffb860;\n"
"    background:transparent;\n"
"    font-size:12px;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 81, 31))
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"    color:#ffb860;\n"
"    background:transparent;\n"
"    font-size:12px;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setEnabled(True)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 150, 171, 21))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setPointSize(-1)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(350, 60, 81, 61))
        self.toolButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pref1/images/AddReviewsIcon.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon2)
        self.toolButton.setIconSize(QtCore.QSize(35, 35))
        self.toolButton.setObjectName("toolButton")

        Review.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Review)
        self.statusbar.setObjectName("statusbar")
        Review.setStatusBar(self.statusbar)

        self.retranslateUi(Review)
        QtCore.QMetaObject.connectSlotsByName(Review)

    def rate_1(self):
            self.label_rate.setText('1')

    def rate_2(self):
            self.label_rate.setText('2')

    def rate_3(self):
            self.label_rate.setText('3')

    def rate_4(self):
            self.label_rate.setText('4')

    def rate_5(self):
            self.label_rate.setText('5')

    def insert_data(self):
            try:
                    mydb = mysql.connector.connect(
                            host="",
                            user="",
                            password="",
                            database="review_site"
                    )

                    mycursor = mydb.cursor()

                    note = int(self.label_rate.text())
                    print(note)


                    com = self.lineEdit_2.text()
                    URL = self.lineEdit.text()
                    USER = self.lineEdit_4.text()


                    query = ("INSERT INTO REVIEWS (IDSITE,IDUSAGER,NOTESITE,COMSITE) VALUES ((select IDSITE FROM SITES WHERE LIENSITE =%s),(select IDUSAGER FROM USAGER WHERE NOMUS = %s),%s,%s)")

                    mycursor.execute(query, (URL,USER,  note, com))
                    mydb.commit()
                    self.pushButton.setText("review Added")
                    mycursor.close()
                    mydb.close()
            except mysql.connector.Error as e:
                    self.pushButton.setText("Try Again")

    def retranslateUi(self, Review):
        _translate = QtCore.QCoreApplication.translate
        Review.setWindowTitle(_translate("Review", "MainWindow"))
        self.label.setText(_translate("Review", "Review"))
        self.pushButton.setText(_translate("Review", "Submit"))
        self.lineEdit_3.setText(_translate("Review", "           Rate"))
        self.label_2.setText(_translate("Review", "URL"))
        self.label_rate.setText(_translate("Review", "/5"))
        self.label_3.setText(_translate("Review", "Add Review"))
        self.label_4.setText(_translate("Review", "UserName"))


import images

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Review = QtWidgets.QMainWindow()
    ui = Ui_Review()
    ui.setupUi(Review)
    Review.show()
    sys.exit(app.exec_())
